apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-cicd
  template:
    metadata:
      labels:
        app: devops-cicd
    spec:
      containers:
        - name: devops-cicd
          image: adrianwisniewskiit/devops-cicd-pipeline:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi