apiVersion: v1
kind: Service
metadata:
  name: hello-devops-service
spec:
  type: NodePort
  selector:
    app: hello-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080